spring:
  datasource:
    url: TODOPROD
    username: TODOPROD
    password: TODOPROD
  jpa.properties.hibernate:
    # Pour éviter une error d'hibernate (non bloquante) au start. Incompatibilité SpringBoot 2 + Hibernate + Postgresql (https://hibernate.atlassian.net/browse/HHH-12368)
    jdbc.lob.non_contextual_creation: true
  jpa.hibernate.ddl-auto: update
  liquibase.enabled: false

application:
  default-fee: 10
  ipstack:
    url: http://api.ipstack.com
    access-key: TODOPROD
